### PR TITLE
Added offline MEGAN biogenics for 2019.

### PR DESCRIPTION
**Pull request by drnimbusrain**

### CODE REVIEW

**Comment by bbakernoaa** [comment]
Patrick do you have the other years done for this?

**Comment by drnimbusrain** [comment]
@bbakernoaa Yes, they are found on Hera at:  /scratch2/NAGAPE/arl/Patrick.C.Campbell/nexus_emissions/MEGAN_OFFLINE_BVOC/v2019-10/

**Comment by bbakernoaa** [comment]
@drnimbusrain I updated the paths a little to reflect the moved location and fixed a small issue for different years.

**Comment by bbakernoaa** [comment]
Let's merge this thing!

**Pull request merged**
