### PR TITLE
Update the AOD wavelenth to match the versino of P7.1 source code

### PR DESCRIPTION
**Pull request by zhanglikate**

### CODE REVIEW

**Review by bbakernoaa — APPROVED** [review]

**Comment by bbakernoaa** [comment]
Kate have you gotten the p7.1 source code working?

**Comment by zhanglikate** [comment]
@bbakernoaa  Yes. I just got the P7.1 working with my old workflow, but need to update the  namelist. However,  the p7.1-gocart-dev does work with the new workflow as I sent the issue to Raffaele last week. So  I have to switch back to P7.1 with my workflow, but updated  the rc file of dust input as yours.

**Comment by bbakernoaa** [comment]
@zhanglikate ok there will need to be some updates to the AERO_ExtData.rc file as well as there are some additional inputs, specifically with OC.

I'll go ahead and approve this.  Could you outline the steps that you took to get that working in Raffaele's issue? https://github.com/noaa-oar-arl/UFS-Aerosol-Config/issues/14

**Comment by zhanglikate** [comment]
@bbakernoaa I did not update the OC part, because that is not included in the  P7.1, but feature/p7.1-gocart-dev branch. However, the p7.1-gocart-dev does  not work with the new workflow  that Raffaele sent to us. So I just gave up to test the  p7.1-gocart-dev, just use my old workflow with the P7.1.
For P7.1, just need to remove the several line in the file of use/parsing_namelists_FV3.sh in your workflow (your previous workflow, not the one Raffaele just updated):

  fdiag = $FDIAG
  fhmax = $FHMAX
  fhout = $FHOUT
  fhmaxhf = $FHMAX_HF     ! CROW configured
  fhouthf = $FHOUT_HF     ! CROW configured

**Pull request merged**
